name: Robot Framework SEVEREST

on: push

jobs:
  test:
    name: API Tests
    runs-on: ubuntu-latest

    steps:
      - name: CLONAR ARQUIVOS DE REPOSITORIO
        uses: actions/checkout@v4

      - name: CONFIGURAR PYTHON
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: INSTALAÇÃO DAS DEPENDENCIAS
        run: |
          pip install robotframework
          pip install robotframework-requests
          pip install Faker
          pip install robotframework-seleniumlibrary
          # Instalação do Chrome em modo headless
          sudo apt-get update
          sudo apt-get install -y xvfb libxi6 libgconf-2-4
          sudo apt-get install -y google-chrome-stable

      - name: EXECUTANDO OS TESTES DE API DO ROBOT
        env:
          DISPLAY: :99
        run: |
          Xvfb :99 & 
          robot --variable BROWSER:chrome --variable HEADLESS:True --outputdir results/ tests/
      
      - name: Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-framework-report
          path: results

  deploy:
    name: Deploy GitHub Pages 🌐
    runs-on: ubuntu-latest
    needs: test

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: SETUP PAGES
        uses: actions/configure-pages@v2

      - name: DOWNLOAD ARTIFACTS
        uses: actions/download-artifact@v4
        with: 
          name: robot-framework-report
          path: results/

      - name: UPLOAD ARTIFACT
        uses: actions/upload-artifact@v1
        with:
          path: results/

      - name: DEPLOY TO GITHUB PAGES
        id: deployment
        uses: actions/deploy-pages@v1



# name: Robot Framework SEVEREST

# on: push

# jobs:
#   test:
#     name: API Tests
#     runs-on: ubuntu-latest

#     steps:
#     - name: CLONAR ARQUIVOS DE REPOSITORIO
#       uses: actions/checkout@v4

#     - name: CONFIGURAR PYTHON
#       uses: actions/setup-python@v5
#       with:
#         python-version: '3.x'

#     - name: INSTALAÇÃO DAS DEPENDENCIAS
#       run: |
#         pip install robotframework
#         pip install robotframework-requests
#         pip install Faker
#         pip install robotframework-seleniumlibrary

#     - name: EXECUTANDO OS TESTES DE API DO ROBOT
#       run: |
#         robot --outputdir results/ tests/
    
#     - name: Test Report
#       uses: actions/upload-artifact@v4
#       if: always()
#       with:
#         name: robot-framework-report
#         path: results

#   deploy:
#     name: Deploy GitHub Pages 🌐
#     runs-on: ubuntu-latest
#     needs: test

#     permissions:
#       contents: read
#       pages: write
#       id-token: write

#     steps:
#       - name: SETUP PAGES
#         uses: actions/configure-pages@v2

#       - name: DOWNLOAD ARTIFACTS
#         uses: actions/download-artifact@v4
#         with: 
#           name: robot-framework-report
#           path: results/

#       - name: UPLOAD ARTIFACT
#         uses: actions/upload-pages-artifact@v1
#         with:
#           path: results/

#       - name: DEPLOY TO GITHUB PAGES
#         id: deployment
#         uses: actions/deploy-pages@v1




# # name: Robot Framework SEVEREST

# # on: push

# # jobs:
# #   test:
# #     name: API Tests
# #     runs-on: ubuntu-latest

# #     steps:
# #     - name: CLONAR ARQUIVOS DE REPOSITORIO
# #       uses: actions/checkout@v4

# #     - name: CONFIGURAR PYTHON
# #       uses: actions/setup-python@v5
# #       with:
# #         python-version: '3.x'

# #     - name: INSTALAÇÃO DAS DEPENDENCIAS
# #       run: |
# #         pip install robotframework
# #         pip install robotframework-requests
# #         pip install Faker
# #         pip install robotframework-seleniumlibrary

# #     - name: EXECUTANDO OS TESTES DE API DO ROBOT
# #       run: |
# #         robot --outputdir results/ tests/
      
# #     - name: Test Report
# #       uses: actions/upload-artifact@v4
# #       if: always()
# #       with:
# #         name: robot-framework-report
# #         path: results

# #   deploy:
# #     name: Deploy GitHub Pages 🌐
# #     runs-on: ubuntu-latest
# #     needs: 
# #       - test

# #     permissions:
# #       contents: read
# #       pages: write
# #       id-token: write
# #     environment:
# #       name: github-pages    
# #       url: https://Wayslan-in.github.io/SEVEREST/report.html 

# #     steps:
# #       - name: SETUP PAGES
# #         uses: actions/configure-pages@v2

# #       - name: DOWNLOAD ARTIFACTS
# #         uses: actions/download-artifact@v4
# #         with: 
# #           name: robot-framework-report
# #           path: results/

# #       - name: UPLOAD ARTIFACT
# #         uses: actions/upload-pages-artifact@v1
# #         with:
# #           path: results/

# #       - name: DEPLOY TO GITHUB PAGES
# #         id: deployment
# #         uses: actions/deploy-pages@v1

